language: java
addons:
  postgresql: "9.5"
jdk:
#- openjdk7
- oraclejdk8
before_script:
- psql --version
- psql -c "CREATE USER gamification WITH PASSWORD 'gamification';" -U postgres
- psql -U postgres -d postgres -a -f ./psql/dbcreation.sql
- psql -U postgres -d gamificationdb -a -f ./psql/db.sql
script:
- bash make.sh all
sudo: required
