language: java
addons:
  postgresql: "9.5"
jdk:
#- openjdk7
- oraclejdk8
before_script:
  - psql --version
  - sudo su postgres -c "psql -c \"CREATE USER gameadmin WITH PASSWORD 'gameadmin';\""
  - sudo su postgres -c "psql -U postgres -d postgres -a -f ./psql/dbcreation.sql;"
  - sudo su postgres -c "psql -U postgres -d gamificationdb -a -f ./psql/db.sql;"

script:
  - sh _make.sh all
sudo: required
